# Generated by Django 5.1 on 2024-08-21 10:59

import django.db.models.deletion
import topFive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('defense', models.IntegerField(default=topFive.models.get_default_defense)),
                ('offense', models.IntegerField(default=topFive.models.get_default_offense)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=topFive.models.get_default_age)),
                ('height', models.FloatField(default=topFive.models.get_default_height)),
                ('position', models.IntegerField(default=topFive.models.get_default_position)),
                ('speed', models.IntegerField(default=topFive.models.get_default_stat)),
                ('strength', models.IntegerField(default=topFive.models.get_default_stat)),
                ('stamina', models.IntegerField(default=topFive.models.get_default_stat)),
                ('shooting3', models.IntegerField(default=topFive.models.get_default_stat)),
                ('shooting2', models.IntegerField(default=topFive.models.get_default_stat)),
                ('jumping', models.IntegerField(default=topFive.models.get_default_stat)),
                ('defense', models.IntegerField(default=topFive.models.get_default_stat)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('budget', models.IntegerField(default=1000000)),
                ('points', models.IntegerField(default=0)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.IntegerField(default=0)),
                ('arena', models.CharField(max_length=100)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='topFive.coach')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topFive.league')),
                ('players', models.ManyToManyField(blank=True, related_name='teams', to='topFive.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topFive.team'),
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='topFive.team'),
        ),
    ]
