# Generated by Django 4.2.15 on 2024-09-01 09:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import topFive.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('arena_name', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('defense', models.IntegerField(default=topFive.models.get_default_defense)),
                ('offense', models.IntegerField(default=topFive.models.get_default_offense)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=topFive.models.get_default_age)),
                ('height', models.DecimalField(decimal_places=2, default=topFive.models.get_default_height, max_digits=10)),
                ('position', models.IntegerField(default=topFive.models.get_default_position)),
                ('position_name', models.CharField(blank=True, editable=False, max_length=20)),
                ('speed', models.IntegerField(default=topFive.models.get_default_stat)),
                ('strength', models.IntegerField(default=topFive.models.get_default_stat)),
                ('stamina', models.IntegerField(default=topFive.models.get_default_stat)),
                ('shooting3', models.IntegerField(default=topFive.models.get_default_stat)),
                ('shooting2', models.IntegerField(default=topFive.models.get_default_stat)),
                ('jumping', models.IntegerField(default=topFive.models.get_default_stat)),
                ('defense', models.IntegerField(default=topFive.models.get_default_stat)),
                ('rating', models.IntegerField(default=0, editable=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('transfer_list', models.BooleanField(default=True)),
                ('free_agent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('budget', models.IntegerField(default=1000000)),
                ('points', models.IntegerField(default=0)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.IntegerField(default=0)),
                ('arena', models.CharField(max_length=100)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='topFive.coach')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topFive.league')),
                ('players', models.ManyToManyField(blank=True, related_name='teams', to='topFive.player')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('full_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topFive.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('home_team_three_pointers', models.IntegerField(default=0)),
                ('away_team_three_pointers', models.IntegerField(default=0)),
                ('home_team_two_pointers', models.IntegerField(default=0)),
                ('away_team_two_pointers', models.IntegerField(default=0)),
                ('home_team_free_throws', models.IntegerField(default=0)),
                ('away_team_free_throws', models.IntegerField(default=0)),
                ('match_date', models.DateTimeField()),
                ('match_time', models.TimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, default='Not Played', max_length=50)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='topFive.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='topFive.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topFive.league')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='topFive.team'),
        ),
        migrations.AddField(
            model_name='league',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission'),
        ),
    ]
