# Generated by Django 5.1 on 2024-08-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topFive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='arena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
