# Generated by Django 5.1 on 2024-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topFive', '0002_league_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='arena_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
