# Generated by Django 5.1 on 2024-08-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topFive', '0003_customuser_arena_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='arena',
        ),
    ]
