# Generated by Django 4.2.13 on 2024-08-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topFive', '0004_delete_player_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
