# Generated by Django 5.1 on 2024-08-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topFive', '0004_remove_league_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player',
            name='transfer_list',
            field=models.BooleanField(default=True),
        ),
    ]
