# Generated by Django 5.1 on 2024-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topFive', '0005_player_price_player_transfer_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='free_agent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
