# Generated by Django 5.1 on 2024-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topFive', '0006_player_free_agent_alter_player_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position_name',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
