# Generated by Django 5.1 on 2024-08-26 13:16

import topFive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topFive', '0007_player_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(decimal_places=2, default=topFive.models.get_default_height, max_digits=10),
        ),
    ]
